### PR TITLE
Np instead of npm-release

### LINKED ISSUE #11: Consider to use 'np' insead of 'npm-release'

### PR DESCRIPTION
**Pull request by jukben**
Close #11 

NP:
- Interactive UI
- Ensures you are publishing from the master branch
- Ensures the working directory is clean and that there are no unpulled changes
- Reinstalls dependencies to ensure your project works with the latest dependency tree
- Runs the tests
- Bumps the version in package.json and npm-shrinkwrap.json (if present) and creates a git tag
- Prevents accidental publishing of pre-release versions under the latest dist-tag
- Publishes the new version to npm, optionally under a dist-tag
- Pushes commits and tags to GitHub

### CODE REVIEW

**Comment by grabbou** [comment]
Thanks, any notable differences? Also, would you mind sending another pull request, this time removing custom eslint config (and prettier) and just using `callstack-io` preset?

CC: @thymikee

**Review by grabbou — APPROVED** [review]

**Comment by thymikee** [comment]
@jukben you'll find it here: https://github.com/callstack-io/eslint-config-callstack-io

**Comment by jukben** [comment]
@grabbou @thymikee It's already there https://github.com/callstack-io/generator-node-module/pull/10 😝

The *np* is better: could recognize yarn / npm project, run test in a freshly installed environment – it's important IMHO.

**Comment by thymikee** [comment]
hm, btw isn't this supposed to be done with `yarn publish`?

**Comment by grabbou** [comment]
Could be, however `np` and `npm-release` have few features I really like,
including:
- interactive UI
- clean directory and master branch
- runs tests
- bumps version for you in package.json
- makes a new tag and pushes to Github

Fewer steps :)

**Comment by thymikee** [comment]
So the diff is in running tests and cleaning directory (afaik yarn doesn't do that currently, but maybe it changed)

**Comment by grabbou** [comment]
Not sure Yarn creates tag on Github (not to confuse with npm registry tag)
and bumps version in package.json for you.

**Comment by thymikee** [comment]
I remember it did, but no time to verify this now :< I'll look at this later

**Comment by jukben** [comment]
@thymikee you are probably right (thanks for that, I haven't used `yarn publish` yet). Anyway, I think that the `clean env, do a fresh install and run tests` is the reason to have it here. 

https://github.com/yarnpkg/yarn/issues/610

**Pull request merged**
